/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package model;

import dao.ClienteDAO;
import dao.ClienteXEventoDAO;
import dao.EventoDAO;
import dao.PagoDAO;
import java.awt.Color;
import java.time.LocalDate;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author miche
 */
public class AgregarPersona extends javax.swing.JFrame {

    private Evento e;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgregarPersona.class.getName());

    /**
     * Creates new form agregarAnticipo
     */
    public AgregarPersona(Evento e) {
        initComponents();
        spiTiquetes.getEditor().getComponent(0).setBackground(new Color(255, 255, 255));
        spiTiquetes.getEditor().getComponent(0).setForeground(new Color(0, 0, 0));
        txtCosto.setFocusable(false);
        setLocationRelativeTo(null);
        this.e = e;
        cargarEventos();
        actualizarCosto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        contenedor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbEvento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAbono = new javax.swing.JTextField();
        spiTiquetes = new javax.swing.JSpinner();
        btnRegistrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        contenedor.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(13, 13, 13, 13);
        contenedor.add(jLabel2, gridBagConstraints);

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(14, 10, 14, 14);
        contenedor.add(txtNombre, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("N. Cédula");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(13, 13, 13, 13);
        contenedor.add(jLabel3, gridBagConstraints);

        txtCedula.setBackground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(14, 10, 14, 14);
        contenedor.add(txtCedula, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Evento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(13, 13, 13, 13);
        contenedor.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("N. Tiquetes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(13, 13, 13, 13);
        contenedor.add(jLabel5, gridBagConstraints);

        cbEvento.setBackground(new java.awt.Color(255, 255, 255));
        cbEvento.addItemListener(this::cbEventoItemStateChanged);
        cbEvento.addActionListener(this::cbEventoActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(14, 10, 14, 14);
        contenedor.add(cbEvento, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Costo del tiquete");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(13, 13, 13, 13);
        contenedor.add(jLabel6, gridBagConstraints);

        txtCosto.setEditable(false);
        txtCosto.setBackground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(14, 10, 14, 14);
        contenedor.add(txtCosto, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Abono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(13, 13, 13, 13);
        contenedor.add(jLabel7, gridBagConstraints);

        txtAbono.setBackground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(14, 10, 14, 14);
        contenedor.add(txtAbono, gridBagConstraints);

        spiTiquetes.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spiTiquetes.addChangeListener(this::spiTiquetesStateChanged);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(14, 10, 14, 14);
        contenedor.add(spiTiquetes, gridBagConstraints);

        btnRegistrar.setBackground(new java.awt.Color(0, 0, 204));
        btnRegistrar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Formulario de Inscripción");

        btnVolver.setBackground(new java.awt.Color(0, 0, 204));
        btnVolver.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel9)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 530, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ellipse 198.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();
        Lista_X_Tour listaxtour = new Lista_X_Tour(e);
        listaxtour.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cbEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEventoActionPerformed

    private void spiTiquetesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spiTiquetesStateChanged
        actualizarCosto();
    }//GEN-LAST:event_spiTiquetesStateChanged

    private void cbEventoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEventoItemStateChanged
        actualizarCosto();
    }//GEN-LAST:event_cbEventoItemStateChanged

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            // ===== 1. Obtener datos =====
            Evento eventoSeleccionado = (Evento) cbEvento.getSelectedItem();
            int idEvento = eventoSeleccionado.getIdEvento();
            if (txtNombre.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese un nombre válido");
                return;
            }

            if (txtCedula.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese una cédula valida");
                return;
            }
            String cedulaTexto = txtCedula.getText().trim();
            if (!cedulaTexto.matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "La cédula debe contener solo números (sin espacios ni guiones)");
                return;
            }
            if (txtAbono.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese un monto de abono");
                return;
            }

            String nombreCompleto = txtNombre.getText().trim();
            int cantidad = (int) spiTiquetes.getValue();
            double costo = Double.parseDouble(txtCosto.getText().trim());
            int cedula = Integer.parseInt(cedulaTexto);
            double abono = Double.parseDouble(txtAbono.getText().trim());

            if (abono > costo) {
                JOptionPane.showMessageDialog(this,
                        "El abono no puede ser mayor al costo total.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            } else if (abono < 0) {
                JOptionPane.showMessageDialog(this,
                        "El abono debe ser mayor o igual a 0.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // ===== 2. Separar nombre y apellido =====
            String nombre;
            String apellidos;

            if (nombreCompleto.contains(" ")) {
                nombre = nombreCompleto.substring(0, nombreCompleto.indexOf(" "));
                apellidos = nombreCompleto.substring(nombreCompleto.indexOf(" ") + 1);
            } else {
                nombre = nombreCompleto;
                apellidos = "";
            }

            // ===== 3. Verificar si cliente existe =====
            boolean clienteExiste = ClienteDAO.existe(cedula, eventoSeleccionado.getIdEvento()); // tenés que crear este método

            if (!clienteExiste) {
                Cliente cliente = new Cliente(cedula, nombre, apellidos);
                ClienteDAO.guardar(cliente);
            }

            // ===== 4. Validar si ya existe inscripción =====
            if (ClienteXEventoDAO.existeInscripcion(cedula, idEvento)) {
                JOptionPane.showMessageDialog(this,
                        "El cliente ya está inscrito en este evento.",
                        "Aviso",
                        JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                // ===== 5. Crear Cliente_X_Evento =====
                Cliente_X_Evento cxe = new Cliente_X_Evento(
                        cedula,
                        idEvento,
                        cantidad,
                        String.valueOf(idEvento) + "_" + String.valueOf(cedula),
                        ""
                );

                // ===== 6. Guardar inscripción =====
                ClienteXEventoDAO.guardar(cxe);

                // ===== 7. Guardar abono como pago
                if (abono > 0) {
                    Pago pago = new Pago();

                    pago.setFecha(LocalDate.now());
                    pago.setMonto(abono);
                    pago.setCedula(cedula);
                    pago.setId_evento(idEvento);
                    pago.setId_pago(PagoDAO.obtenerSiguienteId());

                    PagoDAO.guardar(pago);
                }
                // ===== 8. Éxito =====
                {
                    JOptionPane.showMessageDialog(this,
                            "Cliente registrado correctamente.",
                            "Éxito",
                            JOptionPane.INFORMATION_MESSAGE);
                }
            }

            // ===== 9. Cerrar y volver =====
            dispose();
            Lista_X_Tour listaxtour = new Lista_X_Tour(e);
            listaxtour.setVisible(true);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al guardar: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cargarEventos() {
        try {
            List<Evento> lista = EventoDAO.listar();

            DefaultComboBoxModel<Evento> modelo = new DefaultComboBoxModel<>();

            for (Evento evento : lista) {
                modelo.addElement(evento);
            }

            cbEvento.setModel(modelo);

            // Auto-seleccionar el evento actual
            for (int i = 0; i < cbEvento.getItemCount(); i++) {
                Evento item = cbEvento.getItemAt(i);

                if (item.getIdEvento() == e.getIdEvento()) {
                    cbEvento.setSelectedIndex(i);
                    break;
                }
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void actualizarCosto() {
        Evento seleccionado = (Evento) cbEvento.getSelectedItem();

        int cantidad = (int) spiTiquetes.getValue();
        double costo = cantidad * seleccionado.getMontoPersona();

        txtCosto.setText(String.valueOf(costo));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AgregarPersona(null
        ).setVisible(true)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<Evento> cbEvento;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner spiTiquetes;
    private javax.swing.JTextField txtAbono;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
