/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package model;

import dao.ClienteDAO;
import dao.ClienteXEventoDAO;
import dao.EventoDAO;
import dao.PagoDAO;
import java.awt.Color;
import java.time.LocalDate;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author miche
 */
public class editarPersona extends javax.swing.JFrame {

    private Evento e;
    private int cedula;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(editarPersona.class.getName());

    /**
     * Creates new form agregarAnticipo
     */
    public editarPersona(Evento e, int cedula) {
        initComponents();
        spiTiquetes.getEditor().getComponent(0).setBackground(new Color(255, 255, 255));
        spiTiquetes.getEditor().getComponent(0).setForeground(new Color(0, 0, 0));
        txtEvento.setFocusable(false);
        txtCosto.setFocusable(false);

        setLocationRelativeTo(null);
        this.e = e;
        this.cedula = cedula;
        llenarCampos();
        actualizarCosto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        contenedor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEvento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        spiTiquetes = new javax.swing.JSpinner();
        txtCedula = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        contenedor.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(13, 13, 13, 13);
        contenedor.add(jLabel2, gridBagConstraints);

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(14, 10, 14, 14);
        contenedor.add(txtNombre, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("N. Cédula");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(13, 13, 13, 13);
        contenedor.add(jLabel3, gridBagConstraints);

        txtEvento.setEditable(false);
        txtEvento.setBackground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(14, 10, 14, 14);
        contenedor.add(txtEvento, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Evento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(13, 13, 13, 13);
        contenedor.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("N. Tiquetes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(13, 13, 13, 13);
        contenedor.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Costo del tiquete");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(13, 13, 13, 13);
        contenedor.add(jLabel6, gridBagConstraints);

        txtCosto.setEditable(false);
        txtCosto.setBackground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(14, 10, 14, 14);
        contenedor.add(txtCosto, gridBagConstraints);

        spiTiquetes.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spiTiquetes.addChangeListener(this::spiTiquetesStateChanged);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(14, 10, 14, 14);
        contenedor.add(spiTiquetes, gridBagConstraints);

        txtCedula.setBackground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(14, 10, 14, 14);
        contenedor.add(txtCedula, gridBagConstraints);

        btnGuardar.setBackground(new java.awt.Color(0, 0, 204));
        btnGuardar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        lbTitulo.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbTitulo.setText("Editando a ");

        btnCancelar.setBackground(new java.awt.Color(0, 0, 204));
        btnCancelar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lbTitulo)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 530, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ellipse 198.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
        listaXtour listaxtour = new listaXtour(e);
        listaxtour.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void spiTiquetesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spiTiquetesStateChanged
        actualizarCosto();
    }//GEN-LAST:event_spiTiquetesStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            // ===== 1. Obtener datos =====
            String nombreCompleto = txtNombre.getText().trim();
            int cedulaEditada = Integer.parseInt(txtCedula.getText().trim());
            int cantidad = (int) spiTiquetes.getValue();

            Evento eventoSeleccionado = e;
            int idEvento = eventoSeleccionado.getIdEvento();

            // ===== 2. Separar nombre y apellido =====
            String nombre;
            String apellidos;

            if (nombreCompleto.contains(" ")) {
                nombre = nombreCompleto.substring(0, nombreCompleto.indexOf(" "));
                apellidos = nombreCompleto.substring(nombreCompleto.indexOf(" ") + 1);
            } else {
                nombre = nombreCompleto;
                apellidos = "";
            }

            // ===== 3. Verificar si cliente existe =====
            boolean clienteExiste = ClienteDAO.existe(cedula, eventoSeleccionado.getIdEvento()); // tenés que crear este método

            if (clienteExiste) {
                boolean actualizarCXE = false;
                Cliente_X_Evento cxeActual = new Cliente_X_Evento();
                try {
                    // ===== 4. Editar Cliente =====
                    Cliente nuevoCliente = new Cliente(cedulaEditada, nombre, apellidos);

                    // ===== 5. Verificar registro y modificar =====
                    if (ClienteXEventoDAO.existeInscripcion(cedula, idEvento)) {
                        cxeActual = ClienteXEventoDAO.obtener(cedula, idEvento);

                        if (cedulaEditada != cxeActual.getCedula()) {
                            cxeActual.setCedula(cedulaEditada);
                            actualizarCXE = true;
                        }
                        if (cantidad != cxeActual.getCant_personas()) {
                            cxeActual.setCant_personas(cantidad);
                            actualizarCXE = true;
                        }

                    } else {
                        JOptionPane.showMessageDialog(this,
                                "El cliente no se encuentra registrado en este evento.",
                                "Aviso",
                                JOptionPane.WARNING_MESSAGE);
                    }

                    // ===== 6. Ejecutar actualización =====
                    ClienteDAO.actualizar(cedula, nuevoCliente);
                    if (actualizarCXE) {
                        ClienteXEventoDAO.actualizar(cedula, cxeActual);
                    }

                    List<Pago> pagosCliente = PagoDAO.buscarPorCedulaYEvento(cedula, idEvento);
                    for (Pago p : pagosCliente) {
                        p.setCedula(cedulaEditada);
                        PagoDAO.actualizar(p);
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Error al editar: " + e.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "El cliente con cédula " + cedula + " no encontrado",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // ===== 7. Éxito =====
            {
                JOptionPane.showMessageDialog(this,
                        "Cliente actualizado correctamente.",
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE);
            }

            // ===== 8. Cerrar y volver =====
            dispose();
            listaXtour listaxtour = new listaXtour(e);
            listaxtour.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al actualizar: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void llenarCampos() {
        try {
            boolean clienteExiste = ClienteDAO.existe(cedula, e.getIdEvento()); // tenés que crear este método
            Cliente c = new Cliente();
            if (clienteExiste) {
                c = ClienteDAO.buscarXCedula(cedula);
                Cliente_X_Evento cxe = ClienteXEventoDAO.obtener(cedula, e.getIdEvento());
                lbTitulo.setText("Editando usuario " + c.getNombre());
                txtNombre.setText(c.getNombre() + " " + c.getApellido());
                txtCedula.setText(String.valueOf(cedula));
                txtEvento.setText(String.valueOf(e.getNombre()));
                spiTiquetes.setValue(cxe.getCant_personas());
            } else {
                JOptionPane.showMessageDialog(this,
                        "Cliente no encontrado.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                dispose();

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error encontrar Cliente: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void actualizarCosto() {
        int cantidad = (int) spiTiquetes.getValue();
        double costo = cantidad * e.getMontoPersona();

        txtCosto.setText(String.valueOf(costo));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new editarPersona(null, 0
        ).setVisible(true)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JSpinner spiTiquetes;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtEvento;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
