/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package model;

import dao.ClienteDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author miche
 */
public class listaXtour extends javax.swing.JFrame {

    private ArrayList<Cliente> Clientes;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(listaXtour.class.getName());

    /**
     * Creates new form listaXtour
     */
    public listaXtour(Evento e, int fila) {
        Clientes = new ArrayList<Cliente>();
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        lbEvento.setText(e.getNombre());
        Cargar(e.getIdEvento());
        VerDatos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnAgregarNuevo = new javax.swing.JButton();
        btnAgregarAnticipo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnVerPagos = new javax.swing.JButton();
        cbEvento = new javax.swing.JComboBox<>();
        btnVolver = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        lbEvento = new javax.swing.JLabel();
        listadopasajeros1 = new javax.swing.JLabel();
        lbleclipse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaPersonas.setBackground(new java.awt.Color(255, 255, 255));
        tablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "N. Cédula", "N. Tiquites", "Costo por tiquete", "Abonos", "Fecha de abono", "Pendiente", "Total"
            }
        ));
        jScrollPane1.setViewportView(tablaPersonas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 930, 410));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(0, 1));

        btnAgregarNuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarNuevo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnAgregarNuevo.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarNuevo.setText("Agregar nuevo");
        btnAgregarNuevo.addActionListener(this::btnAgregarNuevoActionPerformed);
        jPanel4.add(btnAgregarNuevo);

        btnAgregarAnticipo.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarAnticipo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnAgregarAnticipo.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarAnticipo.setText("Agregar anticipo");
        btnAgregarAnticipo.addActionListener(this::btnAgregarAnticipoActionPerformed);
        jPanel4.add(btnAgregarAnticipo);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Editar");
        jPanel4.add(jButton1);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Eliminar");
        jPanel4.add(jButton5);

        btnVerPagos.setBackground(new java.awt.Color(255, 255, 255));
        btnVerPagos.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnVerPagos.setForeground(new java.awt.Color(0, 0, 0));
        btnVerPagos.setText("Ver pagos");
        btnVerPagos.addActionListener(this::btnVerPagosActionPerformed);
        jPanel4.add(btnVerPagos);

        cbEvento.setBackground(new java.awt.Color(255, 255, 255));
        cbEvento.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        cbEvento.setForeground(new java.awt.Color(0, 0, 0));
        cbEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Evento" }));
        cbEvento.addActionListener(this::cbEventoActionPerformed);
        jPanel4.add(cbEvento);

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);
        jPanel4.add(btnVolver);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 730));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Capacidad:");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Costo total:");

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 570, 410, 40));

        lbEvento.setBackground(new java.awt.Color(0, 0, 0));
        lbEvento.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lbEvento.setForeground(new java.awt.Color(0, 0, 0));
        lbEvento.setText(".");
        lbEvento.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(lbEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, -1, -1));

        listadopasajeros1.setBackground(new java.awt.Color(0, 0, 0));
        listadopasajeros1.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        listadopasajeros1.setForeground(new java.awt.Color(0, 0, 0));
        listadopasajeros1.setText("Listado de pasajeros");
        listadopasajeros1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(listadopasajeros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        lbleclipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ellipse 198.png"))); // NOI18N
        jPanel1.add(lbleclipse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();
        ListaTour listatour = new ListaTour();
        listatour.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAgregarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNuevoActionPerformed
        dispose();
        agregarPersona agregarpersona = new agregarPersona();
        agregarpersona.setVisible(true);
    }//GEN-LAST:event_btnAgregarNuevoActionPerformed

    private void btnAgregarAnticipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAnticipoActionPerformed
        dispose();
        AgregarAnticipo agregaranticipo = new AgregarAnticipo();
        agregaranticipo.setVisible(true);
    }//GEN-LAST:event_btnAgregarAnticipoActionPerformed

    private void btnVerPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPagosActionPerformed
        dispose();
        desglose_pagos desglose_pagos = new desglose_pagos();
        desglose_pagos.setVisible(true);
    }//GEN-LAST:event_btnVerPagosActionPerformed

    private void cbEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEventoActionPerformed

    private void Cargar(int idEvento) {
        try {
            Clientes = (ArrayList<Cliente>) ClienteDAO.listar(idEvento);
            System.out.println(Clientes);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar los participantes");
            StringBuilder sb = new StringBuilder("Se ha producido una excepción:\n");
            for (StackTraceElement element : e.getStackTrace()) {
                sb.append(element.toString()).append("\n");
            }
            JOptionPane.showMessageDialog(null, sb.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    public void VerDatos() {

        String matriz[][] = new String[Clientes.size()][8];
        Cliente c;
        for (int i = 0; i < Clientes.size(); i++) {
            c = Clientes.get(i);
            matriz[i][0] = c.getNombre() + " " + c.getApellido();
            matriz[i][1] = Integer.toString(c.getCedula());
            matriz[i][2] = c.getApellido();

        }
        tablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "ID", "Nombre", "Fecha", "Capacidad", "Costo",
                    "Tiquetes Vendidos", "Cant. Días", "Detalles"
                }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new listaXtour(null, 0).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAnticipo;
    private javax.swing.JButton btnAgregarNuevo;
    private javax.swing.JButton btnVerPagos;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbEvento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbEvento;
    private javax.swing.JLabel lbleclipse;
    private javax.swing.JLabel listadopasajeros1;
    private javax.swing.JTable tablaPersonas;
    // End of variables declaration//GEN-END:variables
}
