/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package model;

import dao.ClienteDAO;
import dao.ClienteXEventoDAO;
import dao.EventoDAO;
import dao.PagoDAO;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author miche
 */
public class Lista_X_Tour extends javax.swing.JFrame {

    private ArrayList<Cliente> Clientes;
    private List<Cliente_X_Evento> listaCXE;
    private List<Pago> listaPagos;
    private Evento e;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Lista_X_Tour.class.getName());

    /**
     * Creates new form listaXtour
     */
    public Lista_X_Tour(Evento e) {
        Clientes = new ArrayList<Cliente>();
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        this.e = e;
        Cargar(e.getIdEvento());
        cargarEventos();
        VerDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnAgregarNuevo = new javax.swing.JButton();
        btnAgregarAnticipo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVerPagos = new javax.swing.JButton();
        cbEvento = new javax.swing.JComboBox<>();
        btnVolver = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCapacidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGanancias = new javax.swing.JTextField();
        lbEvento = new javax.swing.JLabel();
        listadopasajeros1 = new javax.swing.JLabel();
        lbleclipse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaPersonas.setBackground(new java.awt.Color(255, 255, 255));
        tablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "N. Cédula", "N. Tiquites", "Costo por tiquete", "Abonos", "Fecha de abono", "Total", "Pendiente"
            }
        ));
        jScrollPane1.setViewportView(tablaPersonas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 930, 410));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(0, 1));

        btnAgregarNuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarNuevo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnAgregarNuevo.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarNuevo.setText("Agregar nuevo");
        btnAgregarNuevo.addActionListener(this::btnAgregarNuevoActionPerformed);
        jPanel4.add(btnAgregarNuevo);

        btnAgregarAnticipo.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarAnticipo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnAgregarAnticipo.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarAnticipo.setText("Agregar anticipo");
        btnAgregarAnticipo.addActionListener(this::btnAgregarAnticipoActionPerformed);
        jPanel4.add(btnAgregarAnticipo);

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);
        jPanel4.add(btnEditar);

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        jPanel4.add(btnEliminar);

        btnVerPagos.setBackground(new java.awt.Color(255, 255, 255));
        btnVerPagos.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnVerPagos.setForeground(new java.awt.Color(0, 0, 0));
        btnVerPagos.setText("Ver pagos");
        btnVerPagos.addActionListener(this::btnVerPagosActionPerformed);
        jPanel4.add(btnVerPagos);

        cbEvento.setBackground(new java.awt.Color(255, 255, 255));
        cbEvento.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        cbEvento.setForeground(new java.awt.Color(0, 0, 0));
        cbEvento.setSelectedIndex(-1);
        cbEvento.addItemListener(this::cbEventoItemStateChanged);
        cbEvento.addActionListener(this::cbEventoActionPerformed);
        jPanel4.add(cbEvento);

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);
        jPanel4.add(btnVolver);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 730));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Capacidad:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtCapacidad.setEditable(false);
        txtCapacidad.setBackground(new java.awt.Color(255, 255, 255));
        txtCapacidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCapacidad.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        txtCapacidad.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("  Ganancias: ");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtGanancias.setEditable(false);
        txtGanancias.setBackground(new java.awt.Color(255, 255, 255));
        txtGanancias.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtGanancias.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        txtGanancias.setFocusable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(txtGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)))
        );

        jLabel2.getAccessibleContext().setAccessibleName("Ganancias:");

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, 590, 40));

        lbEvento.setBackground(new java.awt.Color(0, 0, 0));
        lbEvento.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lbEvento.setForeground(new java.awt.Color(0, 0, 0));
        lbEvento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEvento.setText(".");
        lbEvento.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(lbEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, -1));

        listadopasajeros1.setBackground(new java.awt.Color(0, 0, 0));
        listadopasajeros1.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        listadopasajeros1.setForeground(new java.awt.Color(0, 0, 0));
        listadopasajeros1.setText("Listado de pasajeros");
        listadopasajeros1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(listadopasajeros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        lbleclipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ellipse 198.png"))); // NOI18N
        jPanel1.add(lbleclipse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();
        ListaTour listatour = new ListaTour();
        listatour.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAgregarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNuevoActionPerformed
        dispose();
        AgregarPersona agregarpersona = new AgregarPersona(e);
        agregarpersona.setVisible(true);
    }//GEN-LAST:event_btnAgregarNuevoActionPerformed

    private void btnAgregarAnticipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAnticipoActionPerformed
        int fila = tablaPersonas.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un evento");
            return;
        }

        int cedula = Integer.parseInt(tablaPersonas.getValueAt(fila, 1).toString());
        NumberFormat format = NumberFormat.getInstance();
        Number number;
        try {
            number = format.parse(tablaPersonas.getValueAt(fila, 7).toString());
        } catch (Exception ex) {
            System.out.println("Formato de número incorrecto");
            System.out.println(ex);
            number = 0;
        }
        double pendiente = number.doubleValue();

        dispose();
        AgregarAnticipo agregaranticipo = new AgregarAnticipo(e, cedula, pendiente);
        agregaranticipo.setVisible(true);
    }//GEN-LAST:event_btnAgregarAnticipoActionPerformed

    private void btnVerPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPagosActionPerformed
        dispose();
        DesglosePagos desglose_pagos = new DesglosePagos(e);
        desglose_pagos.setVisible(true);
    }//GEN-LAST:event_btnVerPagosActionPerformed

    private void cbEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEventoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = tablaPersonas.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un evento");
            return;
        }
        int cedula = Integer.parseInt(tablaPersonas.getValueAt(fila, 1).toString());
        try {

            String nombre = tablaPersonas.getValueAt(fila, 0).toString();

            int confirmacion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Está seguro de eliminar el apartado de " + nombre + "? \n"
                    + "Esto también borrará los abonos del sistema.",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirmacion == JOptionPane.YES_OPTION) {

                ClienteXEventoDAO.eliminar(cedula, e.getIdEvento());

                PagoDAO.eliminar(cedula, e.getIdEvento());

                Cargar(e.getIdEvento());
                VerDatos();

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar");
            StringBuilder sb = new StringBuilder("Se ha producido una excepción:\n");
            for (StackTraceElement element : e.getStackTrace()) {
                sb.append(element.toString()).append("\n");
            }
            JOptionPane.showMessageDialog(null, sb.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int fila = tablaPersonas.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un evento");
            return;
        }
        int cedula = Integer.parseInt(tablaPersonas.getValueAt(fila, 1).toString());
        dispose();
        EditarPersona editarpersona = new EditarPersona(e, cedula);
        editarpersona.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void cbEventoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEventoItemStateChanged
        Evento seleccionado = (Evento) cbEvento.getSelectedItem();
        this.e = seleccionado;
        Cargar(e.getIdEvento());
        VerDatos();
    }//GEN-LAST:event_cbEventoItemStateChanged

    private void Cargar(int idEvento) {
        lbEvento.setText(e.getNombre());
        try {
            // Clientes del evento
            Clientes = (ArrayList<Cliente>) ClienteDAO.listarXEvento(idEvento);
            System.out.println("Clientes");
            System.out.println(Clientes);

            listaCXE = ClienteXEventoDAO.buscarPorEvento(idEvento);
            System.out.println("ClienteXEvento");
            System.out.println(listaCXE);

            listaPagos = PagoDAO.buscarPorEvento(idEvento);
            System.out.println("Pagos");
            System.out.println(listaPagos);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar los participantes");

            StringBuilder sb = new StringBuilder("Se ha producido una excepción:\n");
            for (StackTraceElement element : e.getStackTrace()) {
                sb.append(element.toString()).append("\n");
            }
            System.out.println(sb.toString());
            JOptionPane.showMessageDialog(null, sb.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void VerDatos() {

        String matriz[][] = new String[Clientes.size()][8];

        for (int i = 0; i < Clientes.size(); i++) {

            Cliente c = Clientes.get(i);

            // Buscar Cliente_X_Evento en memoria
            Cliente_X_Evento cxe = null;
            for (Cliente_X_Evento item : listaCXE) {
                if (item.getCedula() == c.getCedula()) {
                    cxe = item;
                    break;
                }
            }

            int tiquetes = (cxe != null) ? cxe.getCant_personas() : 0;

            double totalAPagar = tiquetes * e.getMontoPersona();

            // Filtrar pagos en memoria
            int abonos = 0;
            double totalPagado = 0;
            LocalDate fechaMasReciente = null;
            System.out.println("Lista Pagos");
            System.out.println(listaPagos);
            for (Pago p : listaPagos) {

                System.out.println(p);
                if (p.getCedula() == c.getCedula()) {

                    abonos++;
                    totalPagado += p.getMonto();

                    if (fechaMasReciente == null || p.getFecha().isAfter(fechaMasReciente)) {
                        fechaMasReciente = p.getFecha();
                    }
                }
            }
            System.out.println(abonos + " " + totalPagado);

            String ultimaFecha = (fechaMasReciente != null) ? fechaMasReciente.toString() : "";

            double pendiente = totalAPagar - totalPagado;

            matriz[i][0] = c.getNombre() + " " + c.getApellido();
            matriz[i][1] = String.valueOf(c.getCedula());
            matriz[i][2] = String.valueOf(tiquetes);
            matriz[i][3] = String.format("%.2f", e.getMontoPersona());
            matriz[i][4] = String.valueOf(abonos);
            matriz[i][5] = ultimaFecha;
            matriz[i][6] = String.format("%.2f", totalPagado);
            matriz[i][7] = String.format("%.2f", pendiente);
        }

        tablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "Nombre", "Cédula", "N. Tiquetes", "Costo por tiquete",
                    "Abonos", "Fecha de abono", "Total", "Pendiente"
                }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        int totalPersonas = 0;
        for (Cliente_X_Evento cxe : listaCXE) {
            totalPersonas += cxe.getCant_personas();
        }
        txtCapacidad.setText(totalPersonas + " / " + e.getCantidadParticipantes());

        double gananciaEstimada = e.getCantidadParticipantes() * e.getMontoPersona();
        double ganaciaReal = 0;
        for (Pago p : listaPagos) {
            ganaciaReal += p.getMonto();

        }
        txtGanancias.setText("₡" + ganaciaReal + " / ₡" + gananciaEstimada);
    }

    private void cargarEventos() {
        try {
            List<Evento> lista = EventoDAO.listar();

            DefaultComboBoxModel<Evento> modelo = new DefaultComboBoxModel<>();

            for (Evento evento : lista) {
                modelo.addElement(evento);
            }

            cbEvento.setModel(modelo);

            // Auto-seleccionar el evento actual
            for (int i = 0; i < cbEvento.getItemCount(); i++) {
                Evento item = cbEvento.getItemAt(i);

                if (item.getIdEvento() == e.getIdEvento()) {
                    cbEvento.setSelectedIndex(i);
                    break;
                }
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Lista_X_Tour(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAnticipo;
    private javax.swing.JButton btnAgregarNuevo;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVerPagos;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<Evento> cbEvento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEvento;
    private javax.swing.JLabel lbleclipse;
    private javax.swing.JLabel listadopasajeros1;
    private javax.swing.JTable tablaPersonas;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtGanancias;
    // End of variables declaration//GEN-END:variables
}
